server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?useSSL=false&charsetEncoding=utf8&verifyServerCertificate=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  thymeleaf:
    cache: false #关闭缓存